services:
  app:
    build: .
    container_name: assurance-backend
    ports:
      - "7090:7090"
    volumes:
      - ./.env.development:/app/.env.development
      - ./.env.production:/app/.env.production
    environment:
      - APP_ENV=production
